/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.event.ChangeListener;
import model.Library;
import service.ServiceGetStringSubmit;

/**
 *
 * @author Welcome
 */
public class view2 extends javax.swing.JFrame {

    /**
     * Creates new form view2
     */
    public Library lib;
    public int index;
    public static view2 myIns;
    
    public static view2 getIns(){
        if (myIns == null) {
            myIns = new view2();
            myIns.lib = new Library();
            myIns.index = 0;
        }
        return myIns;
    }
    
    public void setInit(){
        index = 0;
        setWord(lib.getWord(index).content);
        setMean(lib.getWord(index).translation);
        showMean(true);
        checkShowMean.setSelected(true);
    }
    public view2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWord = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        txtMean = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        checkShowMean = new javax.swing.JCheckBox();
        btnLibrary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtWord.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWord.setText("word");

        btnNext.setText("next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtMean.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtMean.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMean.setText("meaning");

        btnPrev.setText("prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        checkShowMean.setText("show meaning");
        checkShowMean.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkShowMeanStateChanged(evt);
            }
        });
        checkShowMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShowMeanActionPerformed(evt);
            }
        });

        btnLibrary.setText("Library");
        btnLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMean, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkShowMean)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(4, 4, 4)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnLibrary)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnLibrary)
                .addGap(29, 29, 29)
                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtMean, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrev)
                    .addComponent(checkShowMean))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         if (index == lib.getLength()-1){
                index = 0;
            } else {
                index++;
            }
           setWord(lib.getWord(index).content);
           setMean(lib.getWord(index).translation);
    }//GEN-LAST:event_btnNextActionPerformed
    public void nextWord(){
         if (index == lib.getLength()-1){
                index = 0;
            } else {
                index++;
            }
           setWord(lib.getWord(index).content);
           setMean(lib.getWord(index).translation);
    }
    private void btnLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryActionPerformed
        // TODO add your handling code here:
        view1 view11 = view1.getIns();
        view11.addListLibs();
        view11.setVisible(true);
        view2 view22 = view2.getIns();
        view22.setVisible(false);
    }//GEN-LAST:event_btnLibraryActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
         if (index == 0){
                index = lib.getLength()-1;
            } else {
                index--;
            }
            setWord(lib.getWord(index).content);
            setMean(lib.getWord(index).translation);
    }//GEN-LAST:event_btnPrevActionPerformed
    public void prevWord(){
        if (index == 0){
                index = lib.getLength()-1;
            } else {
                index--;
            }
            setWord(lib.getWord(index).content);
            setMean(lib.getWord(index).translation);
    }
    private void checkShowMeanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkShowMeanStateChanged
        if (isShowMean()){
                showMean(true);
            } else {
                showMean(false);
            }
    }//GEN-LAST:event_checkShowMeanStateChanged

    private void checkShowMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkShowMeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkShowMeanActionPerformed
    
//    public void actionNext(ActionListener next){
//        btnNext.addActionListener(next);
//    }
    
    public boolean isShowMean(){
        return checkShowMean.isSelected();
    }
    public void checkShowMean(boolean state){
        checkShowMean.setSelected(state);
    }
    public void showMean(boolean state){
        txtMean.setVisible(state);
    }
    
//    public void actionPrev(ActionListener prev){
//        btnPrev.addActionListener(prev);
//    }
    
    public void changeShowMean(ChangeListener l){
        checkShowMean.addChangeListener(l);
    }
    
    public void setWord(String word){
        txtWord.setText(word);
    }
    
    public void setMean(String mean){
        txtMean.setText(mean);
    }
    
    public void setWordvisi(){
        txtWord.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JCheckBox checkShowMean;
    private javax.swing.JLabel txtMean;
    private javax.swing.JLabel txtWord;
    // End of variables declaration//GEN-END:variables
}
